// address.http

//추가하기
POST http://localhost:8080/rest/address
Content-Type: application/json

{
    "name": "붕어",
    "age": 10,
    "gender": "m",
    "address": "서울시 강남구 역삼동"
}

###

//목록보기
GET http://localhost:8080/rest/address
Content-Type: application/json

###

//수정하기
PUT http://localhost:8080/rest/address/2
Content-Type: application/json

{
    "name": "홍철순",
    "age": 30,
    "gender": "f",
    "address": "서울시 강남구 역삼동"
}

###

//삭제하기
DELETE http://localhost:8080/rest/address/2
Content-Type: application/json
